### PR TITLE
Update bitcoin-abc@0.18.0

### PR DESCRIPTION
**Pull request by quintela**
* Updates bitcoin-abc to 0.18.0
* Fix README.md

### CODE REVIEW

**Comment by quintela** [comment]
Regarding version pining we have two options: 

1. repository pining

"With repository pinning, you can actually pin down the packages to the latest available package version of the selected Alpine Linux version. For example, in Alpine 3.5, the package Node.js might be 2.0, and in Alpine 3.4 it's 1.9. By pinning down the repository to Alpine 3.4, you will always get Node.js 1.9, because Alpine 3.4 is an old version and not updated anymore."

2. package pining

"With package pinning, you can pin down the packages to their respective versions. It lets you specify what version of a package you want, like Node.js in version 1.2.3. Unfortunately Alpine Linux does not keep old packages." 

Thus, as we've figured out the other day, we need to pin Alpine's repository to be able to have a fixed package version of boost-dev.

Let me know how does this sound to you and/or let's discuss this offline.

**Comment by joaopaulofonseca** [comment]
Ok, we'll go with repository pinning then, since Alpine doesn't keep the old package versions for recent  repository versions.

**Comment by JamesCropcho** [comment]
Thanks for continuing to support this well-functioning Docker Image.

With regards to the mission of this PR, i.e. "[u]pdate bitcoin-abc@0.18.0," we sadly have (yet!) not fully succeeded since the tightly-related issue https://github.com/uphold/docker-bitcoin-abc/issues/12 remains unresolved.

How can we get these tags fixed? I don't believe I have the needed permissions, but is there any way I can help?

**Comment by joaopaulofonseca** [comment]
You're right @JamesCropcho, we somehow missed that tag. We'll fix that. Thanks for the heads up!

**Pull request merged**
